version: 2

before:
  hooks:
    - go mod tidy

builds:
  # macOS build (no CGO needed)
  - id: spank-darwin
    env:
      - CGO_ENABLED=0
      - GOPRIVATE=github.com/taigrr/apple-silicon-accelerometer
    goos:
      - darwin
    goarch:
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

  # Linux build (CGO required for audio)
  - id: spank-linux
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}
    overrides:
      - goos: linux
        goarch: arm64
        env:
          - CGO_ENABLED=1
          - CC=aarch64-linux-gnu-gcc

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

release:
  github:
    owner: taigrr
    name: spank
